# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6a8f9db66511e256c77702e22f71e6c6b76bc60c175b8059236135c3b496b8aec16fe226872e3e1cfe4b548e587302a93233f952e62f5d204bfcb970063f75a

test:
  secret_key_base: f698d5e4ee5e004acc6c6d0aaf99d1d98fb129a965a2972bc0155e4acb8a0db29319e8794ae5a9401d1c4c709f9346e7e62f78af4fd114454e430b3b0efb874b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
